### ISSUE TITLE
put the bare GeoJSON file inside the repo

### ISSUE THREAD

**Issue by gka** [derhuerst/berlin-wall-shape#5]
some people don't want to use npm to require geo data

**Comment by derhuerst** [comment]
I'm worried about sacrificing the following things that npm provides:

- convenience: If you have an existing Node project, adding this data is as easy as `npm install berlin-wall-shape`.
- semantic versioning: Right now I can reasonably expect [SemVer](http://semver.org/)-minor versions to work with my existing code base.
- easy installs/updates: Making the update process as seamless as `npm update berlin-wall-shape` will make sure that fixed versions of the data will end up in apps. (This is less important for something as static as the shape of the Berlin wall.)

What workflow do you have in mind?

**Comment by gka** [comment]
the workflow I had in mind goes something like this

* I search online for "berlin wall geojson" and find this Github repository
* the repository contains a file `berlin-wall.geojson` and I download it right away
* I am a happy user and star the repo :)

no need for `npm install` and writing custom JS code (like `fs.writeFileSync(JSON.stringify(shape))` etc) in order to just get the berlin wall shape. 

I am not worried about semantic versioning or `npm update` because all I want is the geojson file.

**Comment by derhuerst** [comment]
And then it will stay there forever, checked into your repo? Doesn't sound like the best workflow.

I will use GitHub releases.

**Comment by gka** [comment]
not my repo, I was referring to this repository, [derhuerst/berlin-wall-shape](https://github.com/derhuerst/berlin-wall-shape).

in fact, I don't want to use the wall GeoJSON programatically at all, I really just needed the file itself. and I can't download it from the source daten.berlin.de without creating an account. the only reason I opened this issue here is that this Github repo shows up as the very first search result for the term "berlin wall geojson" ;-)

using releases would work fine. thanks!

**Comment by derhuerst** [comment]
https://unpkg.com/berlin-wall-shape@1.0.1/index.geo.json

**Comment by derhuerst** [comment]
Closing as solved; the link above will let you download the latest version. Please reopen if you indeed want to use releases.
