### ISSUE TITLE
direct access to Berlin Wall shape file without npm?

### ISSUE THREAD

**Issue by jfsantosm** [derhuerst/berlin-wall-shape#8]
Hi @derhuerst ,

I checked your code, and being honest, it is the first time I deal with npm. I am looking for a shapefile of the berlin wall, and I have not been able to find it. Is it possible from your code to download a geojason, or a shp file to open in Geoda or R?

Thanks,
Felipe

**Comment by derhuerst** [comment]
[The `berlin-wall-shape` package on npm](https://npmjs.com/package/berlin-wall-shape) contains the GeoJSON data.

- You can download the current version (`1.0.1`) from the npm registry via `https://registry.npmjs.org/berlin-wall-shape/-/berlin-wall-shape-1.0.1.tgz` and extract the file from it.
- If you want to rely on (another) third-party service, you can use [unpkg](https://unpkg.com): `https://unpkg.com/berlin-wall-shape@1.0.1/index.geo.json`.
- You can also clone the repo and run the build script locally.

**Comment by jfsantosm** [comment]
Hi @derhuerst,

Thanks for your prompt reply. I was able to access the shapefile.

Best,
 Felipe

**Comment by derhuerst** [comment]
Glad I could help.
